### ISSUE TITLE
Setup with no models error

### ISSUE THREAD

**Issue by rockmantist** [jarcodallo/fastify-objectionjs#35]
Hi i got this error when i try to use the plugin only to do the setup.

**Error: You need to provide a valid array of `objection.js` models.**
at fastifyObjectionjs (/Users/hilman/Code/Work/Side/iam-api-new/node_modules/fastify-objectionjs/plugin.js:43:10)
    at Plugin.exec (/Users/hilman/Code/Work/Side/iam-api-new/node_modules/avvio/plugin.js:89:17)
    at Boot.loadPlugin (/Users/hilman/Code/Work/Side/iam-api-new/node_modules/avvio/plugin.js:187:10)
    at Task.release (/Users/hilman/Code/Work/Side/iam-api-new/node_modules/fastq/queue.js:140:16)
    at worked (/Users/hilman/Code/Work/Side/iam-api-new/node_modules/fastq/queue.js:182:10)
    at /Users/hilman/Code/Work/Side/iam-api-new/node_modules/avvio/plugin.js:190:7
    at done (/Users/hilman/Code/Work/Side/iam-api-new/node_modules/avvio/plugin.js:136:5)
    at check (/Users/hilman/Code/Work/Side/iam-api-new/node_modules/avvio/plugin.js:147:7)
    at processTicksAndRejections (internal/process/task_queues.js:75:11)

fastify-objectionjs 0.2.1
fastify
    .register(require('fastify-objectionjs'), {
        knexConfig: {
            client: 'pg',
            connection: "postgres://username:password@host:port/db",
        }
    })

**Comment by jarcodallo** [comment]
:O, I will fix this soon. Thanks for open the issue @rockmantist

**Comment by jarcodallo** [comment]
Hi @rockmantist, please try with `npm install fastify-objectionjs@0.2.2` and let me know if it's works
